#!/usr/bin/env bash
# Check for the correct number of parameters

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit;
fi

# Assign parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4

export SSH_OPTS="-o StrictHostKeyChecking=no"

scp $SSH_OPTS -o UserKnownHostsFile=/dev/null -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "${USERNAME}"@"${IP}":~/
