#!/usrn/bin/env bash
# Bash script that Creates the file /var/run/myscript.pid containing its PID
trap "echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "exit" SIGQUIT

echo $$ > /var/run/holbertonscript.pid

while ((1)); do
    echo To infinity and beyond
    sleep 10
done
