#!/usrn/bin/env bash
# Bash script that Creates the file /var/run/myscript.pid containing its PID
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT
trap "echo Y U no love me?!" SIGINT

if [ ! -e "$file" ]; then
  touch "$file"
fi

sleep 2 &

echo "$!" > /var/run/myscript.pid

while ((1)); do
    echo To infinity and beyond
    sleep 10
done
