#!/usr/bin/env bash
# Process and PID file

trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

trap "echo Y U no love me?!" SIGINT

file="/var/run/myscript.pid"

echo "$!" > "$file"

while ((1)); do
  echo To infinity and beyond
  sleep 2
done
