#!/usr/bin/env bash
# Manage my process

command="$1"

case "$command" in
  "start")
    bash ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  "stop")
    [ -e "/var/run/my_process.pid" ] && pkill -f './manage_my_process' && rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  "restart")
    "$0" stop >& /dev/null
    "$0" start >& /dev/null
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
